# Generated by Django 5.2.11 on 2026-04-15 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_role_name_alter_user_password_alter_user_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="role",
            name="name",
            field=models.CharField(
                choices=[
                    ("superadmin", "Super Admin"),
                    ("admin", "Admin"),
                    ("counsellor", "Counsellor"),
                    ("student", "Student"),
                    ("parent", "Parent"),
                    ("basic_user", "Basic User"),
                    ("ui_ux", "UI/UX"),
                    ("handholding", "Handholding"),
                ],
                max_length=50,
                unique=True,
            ),
        ),
    ]
