# Generated by Django 5.2.11 on 2026-05-04 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_user_last_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_converted_lead",
            field=models.BooleanField(default=False),
        ),
    ]
