# Generated by Django 5.2.11 on 2026-07-02 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_user_is_converted_lead"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="original_password",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
