# Generated by Django 5.2.11 on 2026-04-15 09:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("counselling_slot", "0005_alter_booking_status"),
        ("event", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="advertisement",
            old_name="status",
            new_name="ad_status",
        ),
        migrations.RenameField(
            model_name="handholdingparticipant",
            old_name="mode",
            new_name="preferred_counselling_mode",
        ),
        migrations.AlterUniqueTogether(
            name="handholdingsession",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="advertisement",
            name="advertisement_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="advertisement",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="certificate",
            name="certificate_status",
            field=models.CharField(
                choices=[("pending", "Pending"), ("issued", "Issued")],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="handholdingparticipant",
            name="show_profile",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="handholdingsession",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="handholdingsession",
            name="ordering",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="handholdingsession",
            name="title",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="handholdingsession",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="advertisement",
            name="ad_end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="advertisement",
            name="ad_platform",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="advertisement",
            name="ad_start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="advertisement",
            name="advertiser_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="advertisement",
            name="amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="advertisement",
            name="contact_mobile",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name="certificate",
            name="certificate_file",
            field=models.FileField(blank=True, null=True, upload_to="certificates/"),
        ),
        migrations.AlterField(
            model_name="certificate",
            name="program_type",
            field=models.CharField(
                blank=True,
                choices=[("handholding", "Handholding")],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="certificate",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="handholdingparticipant",
            name="full_address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="handholdingparticipant",
            name="total_sessions",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="HandHoldingParticipantSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_no", models.PositiveIntegerField()),
                ("session_date", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_booked", "Not Booked"),
                            ("booked", "Booked"),
                            ("in_progress", "In Progress"),
                            ("rescheduled", "Rescheduled"),
                            ("completed", "Completed"),
                            ("pending", "Pending"),
                            ("cancelled", "Cancelled"),
                        ],
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "conducted_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="conducted_handholding_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "handholding_participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="event.handholdingparticipant",
                    ),
                ),
                (
                    "handholding_session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="event.handholdingsession",
                    ),
                ),
                (
                    "slot",
                    models.ForeignKey(
                        blank=True,
                        db_column="slot_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="counselling_slot.slot",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="handholdingsession",
            name="conducted_by",
        ),
        migrations.RemoveField(
            model_name="handholdingsession",
            name="notes",
        ),
        migrations.RemoveField(
            model_name="handholdingsession",
            name="participant",
        ),
        migrations.RemoveField(
            model_name="handholdingsession",
            name="session_date",
        ),
        migrations.RemoveField(
            model_name="handholdingsession",
            name="session_no",
        ),
        migrations.RemoveField(
            model_name="handholdingsession",
            name="status",
        ),
    ]
