# Generated by Django 5.2.11 on 2026-04-15 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0002_rename_status_advertisement_ad_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="handholdingparticipantsession",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
