# Generated by Django 5.2.11 on 2026-04-16 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0003_handholdingparticipantsession_updated_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="CertificateTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "template_file",
                    models.ImageField(upload_to="certificate_templates/"),
                ),
                ("name_x", models.IntegerField(default=0)),
                ("name_y", models.IntegerField(default=800)),
                ("date_x", models.IntegerField(default=0)),
                ("date_y", models.IntegerField(default=950)),
                ("name_font_size", models.IntegerField(default=80)),
                ("date_font_size", models.IntegerField(default=45)),
                ("text_color", models.CharField(default="252,252,200", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name="certificate",
            name="template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="certificates",
                to="event.certificatetemplate",
            ),
        ),
    ]
