# Generated by Django 5.2.11 on 2026-04-23 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0004_certificatetemplate_certificate_template"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="event_date",
        ),
        migrations.RemoveField(
            model_name="event",
            name="institute_name",
        ),
        migrations.RemoveField(
            model_name="event",
            name="location",
        ),
        migrations.RemoveField(
            model_name="event",
            name="status",
        ),
        migrations.RemoveField(
            model_name="event",
            name="title",
        ),
        migrations.AddField(
            model_name="advertisement",
            name="ad_end_time",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="advertisement",
            name="ad_start_time",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="event_end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="event_end_time",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="event_start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="event_start_time",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="payment_method",
            field=models.CharField(
                blank=True,
                choices=[("cash", "Cash"), ("upi", "UPI")],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="payment_type",
            field=models.CharField(
                blank=True,
                choices=[("online", "Online"), ("offline", "Offline")],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="registration_link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="seminar_webinar_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="session_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("upcoming", "Upcoming"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="transaction_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="venue_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("college", "College"),
                    ("corporate", "Corporate"),
                    ("firm", "Firm"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="concerned_person_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="concerned_person_mobile",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="concerned_person_name",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="event_mode",
            field=models.CharField(
                blank=True,
                choices=[("online", "Online"), ("offline", "Offline")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="event_type",
            field=models.CharField(
                blank=True,
                choices=[("seminar", "Seminar"), ("webinar", "Webinar")],
                max_length=20,
                null=True,
            ),
        ),
    ]
