# Generated by Django 5.2.11 on 2026-05-04 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0005_remove_event_event_date_remove_event_institute_name_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="advertisement",
            old_name="ad_end_date",
            new_name="ad_date",
        ),
        migrations.RemoveField(
            model_name="advertisement",
            name="ad_end_time",
        ),
        migrations.RemoveField(
            model_name="advertisement",
            name="ad_start_date",
        ),
        migrations.RemoveField(
            model_name="advertisement",
            name="ad_start_time",
        ),
    ]
