# Generated by Django 5.2.11 on 2026-07-16 13:30

import backend.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0006_rename_ad_end_date_advertisement_ad_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="certificate",
            name="certificate_file",
            field=models.FileField(
                blank=True,
                null=True,
                storage=backend.storage.PublicMediaStorage(),
                upload_to="certificates/",
            ),
        ),
        migrations.AlterField(
            model_name="certificatetemplate",
            name="template_file",
            field=models.ImageField(
                storage=backend.storage.PublicMediaStorage(),
                upload_to="certificate_templates/",
            ),
        ),
        migrations.AlterField(
            model_name="handholdingparticipant",
            name="photo",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=backend.storage.PublicMediaStorage(),
                upload_to="handholding/photos/",
            ),
        ),
        migrations.AlterField(
            model_name="handholdingparticipant",
            name="resume_file",
            field=models.FileField(
                blank=True,
                null=True,
                storage=backend.storage.PrivateMediaStorage(),
                upload_to="handholding/resumes/",
            ),
        ),
    ]
