# Generated by Django 5.2.11 on 2026-03-12 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exam", "0002_alter_exam_id_alter_userexam_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userexam",
            name="exam",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="exam.exam",
            ),
        ),
        migrations.AlterField(
            model_name="userexam",
            name="status",
            field=models.CharField(
                choices=[
                    ("not_started", "Not Started"),
                    ("in_progress", "In Progress"),
                    ("pending_approval", "Pending Approval"),
                    ("completed", "Completed"),
                ],
                default="not_started",
                max_length=200,
            ),
        ),
    ]
