# Generated by Django 5.2.11 on 2026-03-27 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exam", "0003_alter_userexam_exam_alter_userexam_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="userexam",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
