# Generated by Django 5.2.11 on 2026-06-18 07:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exam", "0004_userexam_description"),
        ("program_package", "0007_answer_package_answer_program_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="userexam",
            name="package",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="program_package.package",
            ),
        ),
        migrations.AddField(
            model_name="userexam",
            name="program",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="program_package.program",
            ),
        ),
        migrations.AddConstraint(
            model_name="userexam",
            constraint=models.UniqueConstraint(
                fields=("user", "program", "package"),
                name="unique_user_program_package_exam",
            ),
        ),
    ]
