# Generated by Django 5.2.11 on 2026-07-03 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exam", "0005_userexam_package_userexam_program_and_more"),
        (
            "lead_registration",
            "0010_emailotp_remove_stream_program_lead_parent_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="CareerFuturaTest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(blank=True, max_length=100, null=True)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=20)),
                ("password", models.CharField(max_length=255)),
                ("study_class", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "qualification_status",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("type", models.CharField(blank=True, max_length=100, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="career_futura_tests",
                        to="lead_registration.studentprofile",
                    ),
                ),
            ],
        ),
    ]
