# Generated by Django 5.2.11 on 2026-03-13 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0001_initial"),
        ("program_package", "0003_package_aptitude_test_package_link_url_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="contentpackage",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="content",
            name="program",
        ),
        migrations.AddField(
            model_name="contentpackage",
            name="program",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="program_package.program",
            ),
        ),
        migrations.AlterField(
            model_name="contentpackage",
            name="content",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="content.content",
            ),
        ),
        migrations.AlterField(
            model_name="contentpackage",
            name="package",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="program_package.package",
            ),
        ),
    ]
