# Generated by Django 5.2.11 on 2026-06-18 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0002_alter_contentpackage_unique_together_and_more"),
        (
            "lead_registration",
            "0009_stream_created_at_stream_is_active_stream_program_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="content",
            name="is_student_visible",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="contentpackage",
            name="stream",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="lead_registration.stream",
            ),
        ),
    ]
