# Generated by Django 5.2.11 on 2026-07-02 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0003_content_is_student_visible_contentpackage_stream"),
        (
            "lead_registration",
            "0009_stream_created_at_stream_is_active_stream_program_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "content",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_contents",
                        to="content.content",
                    ),
                ),
                (
                    "student_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_contents",
                        to="lead_registration.studentprofile",
                    ),
                ),
            ],
            options={
                "unique_together": {("student_profile", "content")},
            },
        ),
    ]
