# Generated by Django 5.2.11 on 2026-07-16 13:30

import backend.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0004_studentcontent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="content",
            name="file_url",
            field=models.FileField(
                blank=True,
                null=True,
                storage=backend.storage.PrivateMediaStorage(),
                upload_to="content_files/",
            ),
        ),
        migrations.AlterField(
            model_name="content",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=backend.storage.PublicMediaStorage(),
                upload_to="content_images/",
            ),
        ),
    ]
