# Generated by Django 5.2.11 on 2026-02-17 09:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("exam", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file_path",
                    models.FileField(blank=True, null=True, upload_to="reports/"),
                ),
                (
                    "report_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("locked", "Locked"),
                            ("unlocked", "Unlocked"),
                            ("pending_uploaded", "Pending Uploaded"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("review_required", models.BooleanField(default=False)),
                ("uploaded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="exam.exam"
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "related_type",
                    models.CharField(
                        choices=[
                            ("report", "Report"),
                            ("certificate", "Certificate"),
                            ("paid_doc", "Paid Document"),
                        ],
                        max_length=20,
                    ),
                ),
                ("related_id", models.PositiveIntegerField()),
                ("review_text", models.TextField()),
                ("rating", models.IntegerField()),
                ("is_shared", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
