# Generated by Django 5.2.11 on 2026-03-12 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exam", "0003_alter_userexam_exam_alter_userexam_status"),
        ("report", "0002_alter_report_id_alter_review_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="exam",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="exam.exam",
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="report_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("not_received", "Not Received"),
                    ("received_locked", "Received Locked"),
                    ("received_unlocked", "Received Unlocked"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
