# Generated by Django 5.2.11 on 2026-04-10 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("report", "0003_alter_report_exam_alter_report_report_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="review_status",
            field=models.CharField(
                choices=[
                    ("not_submitted", "Not Submitted"),
                    ("in_process", "In Process"),
                    ("pending_approval", "Pending Approval"),
                    ("submitted", "Submitted"),
                ],
                default="not_submitted",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="review",
            name="rating",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="review",
            name="related_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="review",
            name="related_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("report", "Report"),
                    ("certificate", "Certificate"),
                    ("paid_doc", "Paid Document"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="review_text",
            field=models.TextField(blank=True, null=True),
        ),
    ]
