# Generated by Django 5.2.11 on 2026-06-11 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("program_package", "0006_landingpage"),
        ("report", "0004_review_review_status_review_updated_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="package",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="program_package.package",
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="program",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="program_package.program",
            ),
        ),
    ]
