# Generated by Django 5.2.11 on 2026-06-18 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("report", "0005_report_package_report_program"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="file_path1",
            field=models.FileField(blank=True, null=True, upload_to="reports/"),
        ),
        migrations.AddField(
            model_name="report",
            name="file_path1_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="report",
            name="file_path2",
            field=models.FileField(blank=True, null=True, upload_to="reports/"),
        ),
        migrations.AddField(
            model_name="report",
            name="file_path2_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="report",
            name="file_path_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="report",
            name="report_status_v2",
            field=models.CharField(
                blank=True,
                choices=[
                    ("not_received", "Not Received"),
                    ("received_locked", "Received Locked"),
                    ("received_unlocked", "Received Unlocked"),
                    ("v1_not_received", "Not Received"),
                    ("v2_not_received", "Not Received"),
                    ("v3_not_received", "Not Received"),
                    ("v1_received", "V1 Received"),
                    ("v2_received", "V2 Received"),
                    ("v3_received", "V3 Received"),
                ],
                default="v2_not_received",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="report_status_v3",
            field=models.CharField(
                blank=True,
                choices=[
                    ("not_received", "Not Received"),
                    ("received_locked", "Received Locked"),
                    ("received_unlocked", "Received Unlocked"),
                    ("v1_not_received", "Not Received"),
                    ("v2_not_received", "Not Received"),
                    ("v3_not_received", "Not Received"),
                    ("v1_received", "V1 Received"),
                    ("v2_received", "V2 Received"),
                    ("v3_received", "V3 Received"),
                ],
                default="v3_not_received",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="report_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("not_received", "Not Received"),
                    ("received_locked", "Received Locked"),
                    ("received_unlocked", "Received Unlocked"),
                    ("v1_not_received", "Not Received"),
                    ("v2_not_received", "Not Received"),
                    ("v3_not_received", "Not Received"),
                    ("v1_received", "V1 Received"),
                    ("v2_received", "V2 Received"),
                    ("v3_received", "V3 Received"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
