# Generated by Django 5.2.11 on 2026-07-02 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("report", "0006_report_file_path1_report_file_path1_count_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="report_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("not_received", "Not Received"),
                    ("received_locked", "Received Locked"),
                    ("received_unlocked", "Received Unlocked"),
                    ("v1_not_received", "V1 Not Received"),
                    ("v2_not_received", "V2 Not Received"),
                    ("v3_not_received", "V3 Not Received"),
                    ("v1_received", "V1 Received"),
                    ("v2_received", "V2 Received"),
                    ("v3_received", "V3 Received"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="report_status_v2",
            field=models.CharField(
                blank=True,
                choices=[
                    ("not_received", "Not Received"),
                    ("received_locked", "Received Locked"),
                    ("received_unlocked", "Received Unlocked"),
                    ("v1_not_received", "V1 Not Received"),
                    ("v2_not_received", "V2 Not Received"),
                    ("v3_not_received", "V3 Not Received"),
                    ("v1_received", "V1 Received"),
                    ("v2_received", "V2 Received"),
                    ("v3_received", "V3 Received"),
                ],
                default="v2_not_received",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="report_status_v3",
            field=models.CharField(
                blank=True,
                choices=[
                    ("not_received", "Not Received"),
                    ("received_locked", "Received Locked"),
                    ("received_unlocked", "Received Unlocked"),
                    ("v1_not_received", "V1 Not Received"),
                    ("v2_not_received", "V2 Not Received"),
                    ("v3_not_received", "V3 Not Received"),
                    ("v1_received", "V1 Received"),
                    ("v2_received", "V2 Received"),
                    ("v3_received", "V3 Received"),
                ],
                default="v3_not_received",
                max_length=50,
                null=True,
            ),
        ),
    ]
