# Generated by Django 5.2.11 on 2026-07-16 13:30

import backend.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("report", "0007_alter_report_report_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="file_path",
            field=models.FileField(
                blank=True,
                null=True,
                storage=backend.storage.PrivateMediaStorage(),
                upload_to="reports/",
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="file_path1",
            field=models.FileField(
                blank=True,
                null=True,
                storage=backend.storage.PrivateMediaStorage(),
                upload_to="reports/",
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="file_path2",
            field=models.FileField(
                blank=True,
                null=True,
                storage=backend.storage.PrivateMediaStorage(),
                upload_to="reports/",
            ),
        ),
    ]
