# Generated by Django 5.2.11 on 2026-02-18 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "counselling_slot",
            "0002_alter_booking_id_alter_bookingcounsellor_id_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="slot",
            name="mode",
            field=models.CharField(
                blank=True,
                choices=[("online", "Online"), ("offline", "Offline")],
                max_length=20,
                null=True,
            ),
        ),
    ]
