# Generated by Django 5.2.11 on 2026-03-12 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("counselling_slot", "0003_alter_slot_mode"),
    ]

    operations = [
        migrations.AddField(
            model_name="counsellingnote",
            name="file1",
            field=models.FileField(
                blank=True, null=True, upload_to="counselling_notes/"
            ),
        ),
        migrations.AddField(
            model_name="counsellingnote",
            name="file2",
            field=models.FileField(
                blank=True, null=True, upload_to="counselling_notes/"
            ),
        ),
        migrations.AddField(
            model_name="counsellingnote",
            name="file3",
            field=models.FileField(
                blank=True, null=True, upload_to="counselling_notes/"
            ),
        ),
        migrations.AddField(
            model_name="counsellingnote",
            name="file4",
            field=models.FileField(
                blank=True, null=True, upload_to="counselling_notes/"
            ),
        ),
        migrations.AddField(
            model_name="counsellingnote",
            name="file5",
            field=models.FileField(
                blank=True, null=True, upload_to="counselling_notes/"
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="slot",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="counselling_slot.slot",
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[
                    ("not_booked", "Not Booked"),
                    ("booked", "Booked"),
                    ("rescheduled", "Rescheduled"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                default="booked",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="counsellingnote",
            name="booking",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="counselling_slot.booking",
            ),
        ),
        migrations.AlterField(
            model_name="counsellingnote",
            name="counsellor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="counselling_slot.counsellor",
            ),
        ),
        migrations.AlterField(
            model_name="counsellingnote",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
    ]
