# Generated by Django 5.2.11 on 2026-03-27 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "counselling_slot",
            "0004_counsellingnote_file1_counsellingnote_file2_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[
                    ("not_booked", "Not Booked"),
                    ("booked", "Booked"),
                    ("rescheduled", "Rescheduled"),
                    ("completed", "Completed"),
                    ("pending", "Pending"),
                    ("cancelled", "Cancelled"),
                ],
                default="booked",
                max_length=20,
            ),
        ),
    ]
