# Generated by Django 5.2.11 on 2026-04-23 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("counselling_slot", "0005_alter_booking_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="slot",
            name="is_handholding_session_available",
            field=models.BooleanField(default=True),
        ),
    ]
