# Generated by Django 5.2.11 on 2026-05-25 03:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("counselling_slot", "0006_slot_is_handholding_session_available"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="slot",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="slot",
            constraint=models.UniqueConstraint(
                fields=("counsellor", "date", "start_time"),
                name="unique_counsellor_date_start_time",
            ),
        ),
    ]
