# Generated by Django 5.2.11 on 2026-06-11 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("counselling_slot", "0007_alter_slot_unique_together_and_more"),
        ("program_package", "0006_landingpage"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="package",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="program_package.package",
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="program",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="program_package.program",
            ),
        ),
        migrations.AddField(
            model_name="counsellingnote",
            name="package",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="program_package.package",
            ),
        ),
        migrations.AddField(
            model_name="counsellingnote",
            name="program",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="program_package.program",
            ),
        ),
    ]
