# Generated by Django 5.2.11 on 2026-07-16 13:30

import backend.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("counselling_slot", "0008_booking_package_booking_program_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="counsellingnote",
            name="file1",
            field=models.FileField(
                blank=True,
                null=True,
                storage=backend.storage.PrivateMediaStorage(),
                upload_to="counselling_notes/",
            ),
        ),
        migrations.AlterField(
            model_name="counsellingnote",
            name="file2",
            field=models.FileField(
                blank=True,
                null=True,
                storage=backend.storage.PrivateMediaStorage(),
                upload_to="counselling_notes/",
            ),
        ),
        migrations.AlterField(
            model_name="counsellingnote",
            name="file3",
            field=models.FileField(
                blank=True,
                null=True,
                storage=backend.storage.PrivateMediaStorage(),
                upload_to="counselling_notes/",
            ),
        ),
        migrations.AlterField(
            model_name="counsellingnote",
            name="file4",
            field=models.FileField(
                blank=True,
                null=True,
                storage=backend.storage.PrivateMediaStorage(),
                upload_to="counselling_notes/",
            ),
        ),
        migrations.AlterField(
            model_name="counsellingnote",
            name="file5",
            field=models.FileField(
                blank=True,
                null=True,
                storage=backend.storage.PrivateMediaStorage(),
                upload_to="counselling_notes/",
            ),
        ),
    ]
