# Generated by Django 5.2.11 on 2026-03-12 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("program_package", "0002_alter_package_id_alter_packageexam_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="package",
            name="aptitude_test",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="package",
            name="link_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="userprogrampackage",
            name="package",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="program_package.package",
            ),
        ),
    ]
