# Generated by Django 5.2.11 on 2026-04-15 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "program_package",
            "0004_package_engineering_test_analysis_questionanswer_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="package",
            name="is_handholding",
            field=models.BooleanField(default=False),
        ),
    ]
