# Generated by Django 5.2.11 on 2026-04-16 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("program_package", "0005_package_is_handholding"),
    ]

    operations = [
        migrations.CreateModel(
            name="LandingPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "flyer_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="landing_page_flyers/"
                    ),
                ),
                ("process1", models.CharField(blank=True, max_length=255, null=True)),
                ("process2", models.CharField(blank=True, max_length=255, null=True)),
                ("process3", models.CharField(blank=True, max_length=255, null=True)),
                ("process4", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "contact_details",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "enterprise_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("registration_details1", models.TextField(blank=True, null=True)),
                ("registration_details2", models.TextField(blank=True, null=True)),
                ("registration_details3", models.TextField(blank=True, null=True)),
                ("registration_details4", models.TextField(blank=True, null=True)),
                (
                    "instructions1",
                    models.TextField(blank=True, max_length=255, null=True),
                ),
                (
                    "instructions2",
                    models.TextField(blank=True, max_length=255, null=True),
                ),
                (
                    "instructions3",
                    models.TextField(blank=True, max_length=255, null=True),
                ),
                (
                    "instructions4",
                    models.TextField(blank=True, max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "package",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="program_package.package",
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="program_package.program",
                    ),
                ),
            ],
        ),
    ]
