# Generated by Django 5.2.11 on 2026-03-27 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lead_registration", "0003_lead_specialization_lead_study_class_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="parentprofile",
            name="background",
        ),
        migrations.AddField(
            model_name="parentprofile",
            name="father_background",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="parentprofile",
            name="location",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="parentprofile",
            name="mother_background",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="studentacademichistory",
            name="board_name",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="studentacademichistory",
            name="coaching_entrance",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="studentacademichistory",
            name="current_class_percentage",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="studentacademichistory",
            name="special_notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="board_exam_year",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="improvement_areas",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="previous_class_percentage",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AlterField(
            model_name="studentacademichistory",
            name="academic_stage",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="studentacademichistory",
            name="end_year",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="studentacademichistory",
            name="start_year",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="studentprofile",
            name="city",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="studentsubjectpreference",
            name="preference_type",
            field=models.CharField(
                choices=[
                    ("like", "Like"),
                    ("dislike", "Dislike"),
                    ("moderate", "Moderate"),
                ],
                max_length=20,
            ),
        ),
    ]
