# Generated by Django 5.2.11 on 2026-04-10 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lead_registration", "0004_remove_parentprofile_background_and_more"),
        ("program_package", "0003_package_aptitude_test_package_link_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lead",
            name="program",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="program_package.program",
            ),
        ),
    ]
