# Generated by Django 5.2.11 on 2026-05-04 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lead_registration", "0005_alter_lead_program"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="dob",
            field=models.DateField(blank=True, null=True),
        ),
    ]
