# Generated by Django 5.2.11 on 2026-05-05 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lead_registration", "0006_lead_dob"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="stream",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="stream",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
