# Generated by Django 5.2.11 on 2026-06-11 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lead_registration", "0007_lead_stream_studentprofile_stream"),
        ("program_package", "0006_landingpage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lead",
            name="program",
        ),
        migrations.AddField(
            model_name="lead",
            name="program",
            field=models.ManyToManyField(
                blank=True, related_name="leads", to="program_package.program"
            ),
        ),
    ]
