# Generated by Django 5.2.11 on 2026-07-02 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "lead_registration",
            "0009_stream_created_at_stream_is_active_stream_program_and_more",
        ),
        ("program_package", "0007_answer_package_answer_program_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailOTP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("otp", models.CharField(max_length=6)),
                ("created_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="stream",
            name="program",
        ),
        migrations.AddField(
            model_name="lead",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="leads",
                to="lead_registration.parentprofile",
            ),
        ),
        migrations.AddField(
            model_name="stream",
            name="programs",
            field=models.ManyToManyField(
                blank=True, related_name="streams", to="program_package.program"
            ),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="otp",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="otp_created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="qualification_status",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="suggested_stream",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
