# Generated by Django 5.2.11 on 2026-08-14 05:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_registration', '0010_emailotp_remove_stream_program_lead_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='global_student_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
