# Generated by Django 5.2.11 on 2026-03-12 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0002_alter_payment_id_alter_payment_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="method",
            field=models.CharField(
                blank=True,
                choices=[("cash", "Cash"), ("upi", "Upi")],
                max_length=200,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_type",
            field=models.CharField(
                blank=True,
                choices=[("online", "Online"), ("offline", "Offline")],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("not_paid", "Not Paid"),
                    ("fully_paid", "Fully Paid"),
                    ("partial_paid", "Partial Paid"),
                    ("verification_pending", "Verification Pending"),
                ],
                default="verification_pending",
                max_length=50,
            ),
        ),
    ]
