# Generated by Django 5.2.11 on 2026-06-11 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0004_alter_payment_amount_alter_payment_package_and_more"),
        ("program_package", "0006_landingpage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="package",
        ),
        migrations.AddField(
            model_name="payment",
            name="package",
            field=models.ManyToManyField(blank=True, to="program_package.package"),
        ),
    ]
