# Generated by Django 5.2.11 on 2026-07-16 13:30

import backend.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0005_remove_payment_package_payment_package"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="proof_file",
            field=models.FileField(
                blank=True,
                null=True,
                storage=backend.storage.PrivateMediaStorage(),
                upload_to="payments/",
            ),
        ),
    ]
